version: 0.0
os: linux
files:
  - source: /
    destination: /home/admin/web/phpmagazine.soyvillareal.com/public_html
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  DownloadBundle:
    - location: scripts/delete_info
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/delete_files
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root