version: 0.0
os: linux
files:
  - source: /
    destination: /home/admin/web/phpmagazine.soyvillareal.com/public_html
    overwrite: true
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/admin/web/phpmagazine.soyvillareal.com/public_html
    owner: root
    group: root
    mode: 777
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root